"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-09-30 06:23:57.632895
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.models.bitacora import BITACORA_INMUTABLE_SQL
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=150), nullable=False),
    sa.Column('correo', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.Enum('admin', 'contador', name='rol_usuario', native_enum=False, create_constraint=False, length=20), nullable=False),
    sa.Column('activo', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("rol IN ('admin', 'contador')", name=op.f('ck_usuarios_rol_usuario')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_usuarios')),
    sa.UniqueConstraint('correo', name=op.f('uq_usuarios_correo'))
    )
    op.create_table('bitacora_auditoria',
    sa.Column('usuario_id', sa.Uuid(), nullable=True),
    sa.Column('entidad', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.Uuid(), nullable=True),
    sa.Column('accion', sa.Enum('CREAR_USUARIO', 'EDITAR_USUARIO', 'CAMBIO_PASSWORD', 'ACTIVAR', 'DESACTIVAR', 'REASIGNAR_EMPRESA', 'CAMBIO_PORCENTAJE', 'EDITAR_MOVIMIENTO', 'ELIMINAR_MOVIMIENTO', 'EDITAR_SALIDA', 'ELIMINAR_SALIDA', 'CIERRE_ENVIADO', 'CIERRE_ERROR', name='accion_bitacora', native_enum=False, create_constraint=False, length=40), nullable=False),
    sa.Column('detalle', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("accion IN ('CREAR_USUARIO', 'EDITAR_USUARIO', 'CAMBIO_PASSWORD', 'ACTIVAR', 'DESACTIVAR', 'REASIGNAR_EMPRESA', 'CAMBIO_PORCENTAJE', 'EDITAR_MOVIMIENTO', 'ELIMINAR_MOVIMIENTO', 'EDITAR_SALIDA', 'ELIMINAR_SALIDA', 'CIERRE_ENVIADO', 'CIERRE_ERROR')", name=op.f('ck_bitacora_auditoria_accion_bitacora')),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_bitacora_auditoria_usuario_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bitacora_auditoria'))
    )
    op.create_index(op.f('ix_bitacora_auditoria_usuario_id'), 'bitacora_auditoria', ['usuario_id'], unique=False)
    op.create_index('ix_bitacora_entidad', 'bitacora_auditoria', ['entidad', 'entidad_id'], unique=False)
    op.create_index('ix_bitacora_fecha', 'bitacora_auditoria', ['fecha'], unique=False)
    op.create_table('empresas',
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sa.String(length=200), nullable=False),
    sa.Column('csf', sa.String(length=100), nullable=False),
    sa.Column('documento_pdf_1_url', sa.String(length=500), nullable=True),
    sa.Column('documento_pdf_2_url', sa.String(length=500), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('banco', sa.String(length=100), nullable=False),
    sa.Column('numero_cuenta', sa.String(length=30), nullable=False),
    sa.Column('clabe', sa.String(length=18), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_empresas_usuario_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_empresas'))
    )
    op.create_index(op.f('ix_empresas_usuario_id'), 'empresas', ['usuario_id'], unique=False)
    op.create_table('salidas_empresa',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('destino', sa.String(length=255), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('monto > 0', name=op.f('ck_salidas_empresa_monto_positivo')),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_salidas_empresa_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_salidas_empresa_usuario_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_salidas_empresa'))
    )
    op.create_index('ix_salidas_empresa_fecha', 'salidas_empresa', ['empresa_id', 'fecha'], unique=False)
    op.create_index(op.f('ix_salidas_empresa_usuario_id'), 'salidas_empresa', ['usuario_id'], unique=False)
    op.create_table('terminales_bancarias',
    sa.Column('empresa_id', sa.Uuid(), nullable=False),
    sa.Column('identificador_terminal', sa.String(length=100), nullable=False),
    sa.Column('activa', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('datos_extra', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], name=op.f('fk_terminales_bancarias_empresa_id_empresas'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terminales_bancarias')),
    sa.UniqueConstraint('empresa_id', 'identificador_terminal', name='uq_terminal_por_empresa')
    )
    op.create_index(op.f('ix_terminales_bancarias_empresa_id'), 'terminales_bancarias', ['empresa_id'], unique=False)
    op.create_table('historial_porcentajes_terminal',
    sa.Column('terminal_id', sa.Uuid(), nullable=False),
    sa.Column('porcentaje', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('fecha_inicio_vigencia', sa.Date(), nullable=False),
    sa.Column('fecha_fin_vigencia', sa.Date(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('fecha_fin_vigencia IS NULL OR fecha_fin_vigencia > fecha_inicio_vigencia', name=op.f('ck_historial_porcentajes_terminal_vigencia_valida')),
    sa.CheckConstraint('porcentaje >= 0 AND porcentaje < 100', name=op.f('ck_historial_porcentajes_terminal_porcentaje_rango')),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminales_bancarias.id'], name=op.f('fk_historial_porcentajes_terminal_terminal_id_terminales_bancarias'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_historial_porcentajes_terminal'))
    )
    op.create_index('ix_historial_terminal_inicio', 'historial_porcentajes_terminal', ['terminal_id', 'fecha_inicio_vigencia'], unique=False)
    op.create_index('uq_historial_abierto_por_terminal', 'historial_porcentajes_terminal', ['terminal_id'], unique=True, postgresql_where=sa.text('fecha_fin_vigencia IS NULL'))
    op.create_table('movimientos_terminal',
    sa.Column('terminal_id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('fecha_movimiento', sa.Date(), nullable=False),
    sa.Column('monto_bruto', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('porcentaje_aplicado', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('monto_neto', sa.Numeric(precision=14, scale=2), sa.Computed('round(monto_bruto * (1 - porcentaje_aplicado / 100), 2)', persisted=True), nullable=False),
    sa.Column('fecha_captura', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('monto_bruto > 0', name=op.f('ck_movimientos_terminal_monto_bruto_positivo')),
    sa.CheckConstraint('porcentaje_aplicado >= 0 AND porcentaje_aplicado < 100', name=op.f('ck_movimientos_terminal_porcentaje_rango')),
    sa.ForeignKeyConstraint(['terminal_id'], ['terminales_bancarias.id'], name=op.f('fk_movimientos_terminal_terminal_id_terminales_bancarias'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], name=op.f('fk_movimientos_terminal_usuario_id_usuarios'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_movimientos_terminal'))
    )
    op.create_index('ix_movimientos_fecha', 'movimientos_terminal', ['fecha_movimiento'], unique=False)
    op.create_index('ix_movimientos_terminal_fecha', 'movimientos_terminal', ['terminal_id', 'fecha_movimiento'], unique=False)
    op.create_index(op.f('ix_movimientos_terminal_usuario_id'), 'movimientos_terminal', ['usuario_id'], unique=False)
    # ### end Alembic commands ###
    op.execute(BITACORA_INMUTABLE_SQL)


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_bitacora_inmutable ON bitacora_auditoria")
    op.execute("DROP FUNCTION IF EXISTS bitacora_inmutable()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movimientos_terminal_usuario_id'), table_name='movimientos_terminal')
    op.drop_index('ix_movimientos_terminal_fecha', table_name='movimientos_terminal')
    op.drop_index('ix_movimientos_fecha', table_name='movimientos_terminal')
    op.drop_table('movimientos_terminal')
    op.drop_index('uq_historial_abierto_por_terminal', table_name='historial_porcentajes_terminal', postgresql_where=sa.text('fecha_fin_vigencia IS NULL'))
    op.drop_index('ix_historial_terminal_inicio', table_name='historial_porcentajes_terminal')
    op.drop_table('historial_porcentajes_terminal')
    op.drop_index(op.f('ix_terminales_bancarias_empresa_id'), table_name='terminales_bancarias')
    op.drop_table('terminales_bancarias')
    op.drop_index(op.f('ix_salidas_empresa_usuario_id'), table_name='salidas_empresa')
    op.drop_index('ix_salidas_empresa_fecha', table_name='salidas_empresa')
    op.drop_table('salidas_empresa')
    op.drop_index(op.f('ix_empresas_usuario_id'), table_name='empresas')
    op.drop_table('empresas')
    op.drop_index('ix_bitacora_fecha', table_name='bitacora_auditoria')
    op.drop_index('ix_bitacora_entidad', table_name='bitacora_auditoria')
    op.drop_index(op.f('ix_bitacora_auditoria_usuario_id'), table_name='bitacora_auditoria')
    op.drop_table('bitacora_auditoria')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
